server {
    listen 80;
    server_name www.foxrove.com;

    return 308 https://foxrove.com$request_uri;
}

server {
    listen 80 default_server;
    server_name _;

    root /usr/share/nginx/html;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }
}
